[package]
edition.workspace = true
license.workspace = true
name = "ff_ext"
version.workspace = true

[lib]
bench = false

[dependencies]
ff.workspace = true
goldilocks.workspace = true
poseidon.workspace = true
serde.workspace = true
