[package]
name = "ff_ext"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
description = "Extra functionality for the ff ((finite fields) crate"
repository.workspace = true
categories.workspace = true
keywords.workspace = true


[dependencies]
serde.workspace = true
goldilocks.workspace = true
ff.workspace = true
poseidon.workspace = true
