[package]
categories.workspace = true
description = "A Risc-V emulator for Ceno"
edition.workspace = true
keywords.workspace = true
license.workspace = true
name = "ceno_emul"
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
anyhow = { version = "1.0", default-features = false }
elf = { version = "0.7.4" }
strum = "0.25.0"
strum_macros = "0.25.3"
tracing = { version = "0.1", default-features = false, features = [
  "attributes",
] }

[dev-dependencies]
ceno-examples = { path = "../examples-builder" }
