[workspace]
members = [
    "goldilocks",
    "multilinear_extensions"
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
ark-std = { version = "0.4", features = ["print-trace"] }
ark-poly = "0.4"
criterion = { version = "0.5", features = ["html_reports"] }
ff = "0.13"
subtle = "2.2.1"
rand_core = "0.6.0"
rand_xorshift = "0.3"
rayon = "1.8"
