[workspace]
exclude = ["guest"]
members = [
  "elf",
  "host",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
version = "0.1.0"

[profile.dev]
lto = "thin"

[profile.release]
lto = "thin"
