[workspace]
members = [
    "frontend",
    "gkr",
    "multilinear_extensions",
    "sumcheck",
    "transcript",
    "mpcs",
    "util"
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
ark-std = { version = "0.4" }
ark-poly = "0.4"
criterion = { version = "0.5", features = ["html_reports"] }
ff = { version = "0.13", features = ["derive"] }
goldilocks = { git = "https://github.com/zhenfeizhang/Goldilocks" }
halo2curves = "0.1.0"
itertools = "0.12"
poseidon = { git = "https://github.com/zhenfeizhang/poseidon" }
serde = { version = "1.0", features = ["derive"] }
subtle = "2.2.1"
rand_core = "0.6.0"
rand_xorshift = "0.3"
rayon = "1.8"
