[workspace]
exclude = ["examples"]
members = [
  "ceno_emul",
  "examples-builder",
  "ceno_rt",
  "gkr",
  "gkr-graph",
  "mpcs",
  "multilinear_extensions",
  "simple-frontend",
  "singer",
  "singer-utils",
  "sumcheck",
  "transcript",
  "ceno_zkvm",
  "poseidon",
]
resolver = "2"

[workspace.package]
categories = ["cryptography", "zk", "blockchain", "ceno"]
edition = "2021"
keywords = ["cryptography", "zk", "blockchain", "ceno"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/scroll-tech/ceno"
version = "0.1.0"

[workspace.dependencies]
ark-std = { version = "0.4" }
# ark-std = { version = "0.4", features = ["print-trace"] }
ark-poly = "0.4"
criterion = { version = "0.5", features = ["html_reports"] }
ff = "0.13"
goldilocks = { git = "https://github.com/zhenfeizhang/Goldilocks" }
halo2curves = "0.1.0"
poseidon = { path = "./poseidon" }
rand_chacha = { version = "0.3.1", features = ["serde1"] }
rand_core = "0.6.4"
rand_xorshift = "0.3"
rayon = "1.10"
serde = { version = "1.0", features = ["derive"] }
subtle = "2.6.1"

[patch."https://github.com/zhenfeizhang/Goldilocks"]
goldilocks = { git = "https://github.com/hero78119/Goldilocks" }

[profile.release]
lto = "thin"
