[package]
name = "transcript"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
description = "Transcript generation for Ceno"
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
ff_ext = { path = "../ff_ext" }
crossbeam-channel = "0.5.13"
ark-std.workspace = true
ff.workspace = true
goldilocks.workspace = true
halo2curves.workspace = true
rayon.workspace = true
serde.workspace = true
poseidon.workspace = true
