[package]
name = "ceno-examples"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true
description = "Build scripts for ceno examples"
