[package]
name = "poseidon"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
goldilocks.workspace = true
serde.workspace = true
unroll = "0.1.5"

[dev-dependencies]
plonky2 = "0.2.2"
rand = "0.8.5"
