[package]
name = "ceno_rt"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
riscv = "0.11.1"
riscv-rt = "0.12.2"
rand = { version = "0.8", default-features = false, features = ["alloc", "small_rng"] }
