[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.riscv_opcodes_flamegraph]
args = ["run", "--package", "zkvm", "--release", "--example", "riscv_opcodes"]
command = "cargo"
env = { "RUST_LOG" = "debug" }
