# # Keeping this for legacy purposes - the commands below in `alias` are based off this configuration.
[unstable]
# build-std = ["core"]
# build-std = ["alloc", "core", "compiler_builtins", "std", "panic_abort", "proc_macro"]
build-std = ["alloc", "core", "compiler_builtins", "std", "panic_abort", "proc_macro"]
# build-std-features = ["compiler-builtins-mem"]
build-std-features = []

# [alias]
# my-check = """check \
#  --target=target2.json
#  """
#  -Zbuild-std=alloc,core,compiler_builtins,std,panic_abort,proc_macro \
#  -Zbuild-std-features=compiler-builtins-mem
#  """

[profile.dev]
panic = "abort"

[build]
# rustflags = ["-C", "passes=loweratomic", "-Zlocation-detail=none"]
target = "my-target.json"

# [alias]
# mozakvm-build = """
#     build --profile mozak-release \
#           --target riscv32im-mozak-mozakvm-elf \
#           -Zbuild-std=alloc,core,compiler_builtins,std,panic_abort,proc_macro \
#           -Zbuild-std-features=compiler-builtins-mem
#     """
# mozakvm-check = """
#     check \
#         --target /home/matthias/scroll/prog/standalone-guest/guest/.cargo/riscv32im-mozak-mozakvm-elf.json \
#         -Zbuild-std=alloc,core,compiler_builtins,std,panic_abort,proc_macro \
#         -Zbuild-std-features=compiler-builtins-mem \
#     """
# mozakvm-clippy = """
#     clippy \
#         --target riscv32im-mozak-mozakvm-elf \
#         -Zbuild-std=alloc,core,compiler_builtins,std,panic_abort,proc_macro \
#         -Zbuild-std-features=compiler-builtins-mem \
#     """
# mozakvm-run = """
#     run --profile mozak-release \
#           --target riscv32im-mozak-mozakvm-elf \
#           -Zbuild-std=alloc,core,compiler_builtins,std,panic_abort,proc_macro \
#           -Zbuild-std-features=compiler-builtins-mem 
#     """
# [target]
# # runner = "examples/scripts/run_script.sh"
# # rustflags = ["-C", "passes=loweratomic", "-Zlocation-detail=none"]

# [env]
# # path where riscv32im-mozak-mozakvm-elf.json lies
# # RUST_TARGET_PATH = { value = ".cargo/", relative = true, force = true }
# # RUST_TARGET_PATH = { value = "/home/matthias/scroll/prog/standalone-guest/guest/.cargo/riscv32im-mozak-mozakvm-elf.json", relative = false, force = true }

# [profile.mozak-dev]
# inherits = "dev"
# panic = "abort"

# # profile for mozakvm binaries
# [profile.mozak-release]
# codegen-units = 1
# inherits = "release"
# lto = "fat"
# opt-level = 3
# panic = "abort"
# strip = true


# # [target.riscv32im-unknown-none-elf]
# # # Why does this fail?
# # # "-C", "passes=loweratomic",
# # rustflags = [
# #   # "-C", "passes=loweratomic",
# #   "-C", "link-arg=-Tmemory.x",
# #   "-C", "link-arg=-Tceno_link.x",
# #   "-Zlocation-detail=none",
# #   # "-Zbuild-std=alloc,core,compiler_builtins,std,panic_abort,proc_macro",
# #   # "-Zbuild-std-features=compiler-builtins-mem"
# # ]

# # [unstable]
# # build-std = ["alloc", "core", "compiler_builtins", "std", "panic_abort", "proc_macro"]

# # [build]
# # target = "riscv32im-unknown-none-elf"

# # [env]
# # # path where riscv32im-mozak-mozakvm-elf.json lies
# # RUST_TARGET_PATH = { value = ".cargo/", relative = true, force = true }

# # [profile.dev]
# # panic = "abort"
# # lto = "thin"

# # [profile.release]
# # lto = true
# # panic = "abort"

# # # [target.riscv32im-mozak-mozakvm-elf]
# # # runner = "examples/scripts/run_script.sh"
# # # rustflags = ["-C", "passes=loweratomic", "-Zlocation-detail=none"]
